# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `addressable` gem.
# Please instead update this file by running `bin/tapioca gem addressable`.


# source://addressable//lib/addressable/version.rb#22
module Addressable; end

# source://addressable//lib/addressable/idna/pure.rb#21
module Addressable::IDNA
  class << self
    # source://addressable//lib/addressable/idna/pure.rb#117
    def _deprecated_unicode_normalize_kc(value); end

    # source://addressable//lib/addressable/idna/pure.rb#67
    def to_ascii(input); end

    # source://addressable//lib/addressable/idna/pure.rb#93
    def to_unicode(input); end

    def unicode_normalize_kc(*args, **_arg1, &block); end

    private

    # source://addressable//lib/addressable/idna/pure.rb#140
    def lookup_unicode_lowercase(codepoint); end

    # source://addressable//lib/addressable/idna/pure.rb#488
    def punycode_adapt(delta, numpoints, firsttime); end

    # source://addressable//lib/addressable/idna/pure.rb#456
    def punycode_basic?(codepoint); end

    # source://addressable//lib/addressable/idna/pure.rb#334
    def punycode_decode(punycode); end

    # source://addressable//lib/addressable/idna/pure.rb#474
    def punycode_decode_digit(codepoint); end

    # source://addressable//lib/addressable/idna/pure.rb#461
    def punycode_delimiter?(codepoint); end

    # source://addressable//lib/addressable/idna/pure.rb#213
    def punycode_encode(unicode); end

    # source://addressable//lib/addressable/idna/pure.rb#466
    def punycode_encode_digit(d); end

    # source://addressable//lib/addressable/idna/pure.rb#132
    def unicode_downcase(input); end
  end
end

# source://addressable//lib/addressable/idna/pure.rb#183
Addressable::IDNA::ACE_MAX_LENGTH = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#40
Addressable::IDNA::ACE_PREFIX = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/idna/pure.rb#172
Addressable::IDNA::COMPOSITION_TABLE = T.let(T.unsafe(nil), Hash)

# source://addressable//lib/addressable/idna/pure.rb#185
Addressable::IDNA::PUNYCODE_BASE = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#189
Addressable::IDNA::PUNYCODE_DAMP = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#192
Addressable::IDNA::PUNYCODE_DELIMITER = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#190
Addressable::IDNA::PUNYCODE_INITIAL_BIAS = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#191
Addressable::IDNA::PUNYCODE_INITIAL_N = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#194
Addressable::IDNA::PUNYCODE_MAXINT = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#196
Addressable::IDNA::PUNYCODE_PRINT_ASCII = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/idna/pure.rb#188
Addressable::IDNA::PUNYCODE_SKEW = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#187
Addressable::IDNA::PUNYCODE_TMAX = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#186
Addressable::IDNA::PUNYCODE_TMIN = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#207
class Addressable::IDNA::PunycodeBadInput < ::StandardError; end

# source://addressable//lib/addressable/idna/pure.rb#209
class Addressable::IDNA::PunycodeBigOutput < ::StandardError; end

# source://addressable//lib/addressable/idna/pure.rb#211
class Addressable::IDNA::PunycodeOverflow < ::StandardError; end

# source://addressable//lib/addressable/idna/pure.rb#163
Addressable::IDNA::UNICODE_DATA = T.let(T.unsafe(nil), Hash)

# source://addressable//lib/addressable/idna/pure.rb#150
Addressable::IDNA::UNICODE_DATA_CANONICAL = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#148
Addressable::IDNA::UNICODE_DATA_COMBINING_CLASS = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#151
Addressable::IDNA::UNICODE_DATA_COMPATIBILITY = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#149
Addressable::IDNA::UNICODE_DATA_EXCLUSION = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#153
Addressable::IDNA::UNICODE_DATA_LOWERCASE = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#154
Addressable::IDNA::UNICODE_DATA_TITLECASE = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#152
Addressable::IDNA::UNICODE_DATA_UPPERCASE = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#182
Addressable::IDNA::UNICODE_MAX_LENGTH = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/idna/pure.rb#36
Addressable::IDNA::UNICODE_TABLE = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/idna/pure.rb#42
Addressable::IDNA::UTF8_REGEX = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/idna/pure.rb#53
Addressable::IDNA::UTF8_REGEX_MULTIBYTE = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#31
class Addressable::URI
  # source://addressable//lib/addressable/uri.rb#830
  def initialize(options = T.unsafe(nil)); end

  # source://addressable//lib/addressable/uri.rb#1889
  def +(uri); end

  # source://addressable//lib/addressable/uri.rb#2239
  def ==(uri); end

  # source://addressable//lib/addressable/uri.rb#2217
  def ===(uri); end

  # source://addressable//lib/addressable/uri.rb#1879
  def absolute?; end

  # source://addressable//lib/addressable/uri.rb#1234
  def authority; end

  # source://addressable//lib/addressable/uri.rb#1274
  def authority=(new_authority); end

  # source://addressable//lib/addressable/uri.rb#1588
  def basename; end

  # source://addressable//lib/addressable/uri.rb#1454
  def default_port; end

  # source://addressable//lib/addressable/uri.rb#2396
  def defer_validation; end

  # source://addressable//lib/addressable/uri.rb#2201
  def display_uri; end

  # source://addressable//lib/addressable/uri.rb#1225
  def domain; end

  # source://addressable//lib/addressable/uri.rb#2271
  def dup; end

  # source://addressable//lib/addressable/uri.rb#2333
  def empty?; end

  # source://addressable//lib/addressable/uri.rb#2406
  def encode_with(coder); end

  # source://addressable//lib/addressable/uri.rb#2253
  def eql?(uri); end

  # source://addressable//lib/addressable/uri.rb#1598
  def extname; end

  # source://addressable//lib/addressable/uri.rb#1810
  def fragment; end

  # source://addressable//lib/addressable/uri.rb#1835
  def fragment=(new_fragment); end

  # source://addressable//lib/addressable/uri.rb#870
  def freeze; end

  # source://addressable//lib/addressable/uri.rb#2263
  def hash; end

  # source://addressable//lib/addressable/uri.rb#1120
  def host; end

  # source://addressable//lib/addressable/uri.rb#1156
  def host=(new_host); end

  # source://addressable//lib/addressable/uri.rb#1178
  def hostname; end

  # source://addressable//lib/addressable/uri.rb#1190
  def hostname=(new_hostname); end

  # source://addressable//lib/addressable/uri.rb#1440
  def inferred_port; end

  # source://addressable//lib/addressable/uri.rb#2417
  def init_with(coder); end

  # source://addressable//lib/addressable/uri.rb#2384
  def inspect; end

  # source://addressable//lib/addressable/uri.rb#1855
  def ip_based?; end

  # source://addressable//lib/addressable/uri.rb#1889
  def join(uri); end

  # source://addressable//lib/addressable/uri.rb#1992
  def join!(uri); end

  # source://addressable//lib/addressable/uri.rb#2007
  def merge(hash); end

  # source://addressable//lib/addressable/uri.rb#2072
  def merge!(uri); end

  # source://addressable//lib/addressable/uri.rb#2164
  def normalize; end

  # source://addressable//lib/addressable/uri.rb#2190
  def normalize!; end

  # source://addressable//lib/addressable/uri.rb#1252
  def normalized_authority; end

  # source://addressable//lib/addressable/uri.rb#1816
  def normalized_fragment; end

  # source://addressable//lib/addressable/uri.rb#1126
  def normalized_host; end

  # source://addressable//lib/addressable/uri.rb#1002
  def normalized_password; end

  # source://addressable//lib/addressable/uri.rb#1535
  def normalized_path; end

  # source://addressable//lib/addressable/uri.rb#1392
  def normalized_port; end

  # source://addressable//lib/addressable/uri.rb#1613
  def normalized_query(*flags); end

  # source://addressable//lib/addressable/uri.rb#896
  def normalized_scheme; end

  # source://addressable//lib/addressable/uri.rb#1485
  def normalized_site; end

  # source://addressable//lib/addressable/uri.rb#947
  def normalized_user; end

  # source://addressable//lib/addressable/uri.rb#1068
  def normalized_userinfo; end

  # source://addressable//lib/addressable/uri.rb#2297
  def omit(*components); end

  # source://addressable//lib/addressable/uri.rb#2324
  def omit!(*components); end

  # source://addressable//lib/addressable/uri.rb#1314
  def origin; end

  # source://addressable//lib/addressable/uri.rb#1333
  def origin=(new_origin); end

  # source://addressable//lib/addressable/uri.rb#996
  def password; end

  # source://addressable//lib/addressable/uri.rb#1025
  def password=(new_password); end

  # source://addressable//lib/addressable/uri.rb#1528
  def path; end

  # source://addressable//lib/addressable/uri.rb#1567
  def path=(new_path); end

  # source://addressable//lib/addressable/uri.rb#1386
  def port; end

  # source://addressable//lib/addressable/uri.rb#1408
  def port=(new_port); end

  # source://addressable//lib/addressable/uri.rb#1607
  def query; end

  # source://addressable//lib/addressable/uri.rb#1641
  def query=(new_query); end

  # source://addressable//lib/addressable/uri.rb#1672
  def query_values(return_type = T.unsafe(nil)); end

  # source://addressable//lib/addressable/uri.rb#1723
  def query_values=(new_query_values); end

  # source://addressable//lib/addressable/uri.rb#1869
  def relative?; end

  # source://addressable//lib/addressable/uri.rb#1774
  def request_uri; end

  # source://addressable//lib/addressable/uri.rb#1786
  def request_uri=(new_request_uri); end

  # source://addressable//lib/addressable/uri.rb#2085
  def route_from(uri); end

  # source://addressable//lib/addressable/uri.rb#2150
  def route_to(uri); end

  # source://addressable//lib/addressable/uri.rb#890
  def scheme; end

  # source://addressable//lib/addressable/uri.rb#917
  def scheme=(new_scheme); end

  # source://addressable//lib/addressable/uri.rb#1467
  def site; end

  # source://addressable//lib/addressable/uri.rb#1506
  def site=(new_site); end

  # source://addressable//lib/addressable/uri.rb#1207
  def tld; end

  # source://addressable//lib/addressable/uri.rb#1215
  def tld=(new_tld); end

  # source://addressable//lib/addressable/uri.rb#2367
  def to_hash; end

  # source://addressable//lib/addressable/uri.rb#2341
  def to_s; end

  # source://addressable//lib/addressable/uri.rb#2341
  def to_str; end

  # source://addressable//lib/addressable/uri.rb#941
  def user; end

  # source://addressable//lib/addressable/uri.rb#970
  def user=(new_user); end

  # source://addressable//lib/addressable/uri.rb#1052
  def userinfo; end

  # source://addressable//lib/addressable/uri.rb#1091
  def userinfo=(new_userinfo); end

  protected

  # source://addressable//lib/addressable/uri.rb#2561
  def force_utf8_encoding_if_needed(str); end

  # source://addressable//lib/addressable/uri.rb#2552
  def remove_composite_values; end

  # source://addressable//lib/addressable/uri.rb#2519
  def replace_self(uri); end

  # source://addressable//lib/addressable/uri.rb#2542
  def split_path(path); end

  # source://addressable//lib/addressable/uri.rb#2476
  def validate; end

  private

  # source://addressable//lib/addressable/uri.rb#2573
  def reset_ivs; end

  class << self
    # source://addressable//lib/addressable/uri.rb#292
    def convert_path(path); end

    # source://addressable//lib/addressable/uri.rb#616
    def encode(uri, return_type = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#403
    def encode_component(component, character_class = T.unsafe(nil), upcase_encoded = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#616
    def escape(uri, return_type = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#403
    def escape_component(component, character_class = T.unsafe(nil), upcase_encoded = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#740
    def form_encode(form_values, sort = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#793
    def form_unencode(encoded_value); end

    # source://addressable//lib/addressable/uri.rb#191
    def heuristic_parse(uri, hints = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#1369
    def ip_based_schemes; end

    # source://addressable//lib/addressable/uri.rb#343
    def join(*uris); end

    # source://addressable//lib/addressable/uri.rb#552
    def normalize_component(component, character_class = T.unsafe(nil), leave_encoded = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#2440
    def normalize_path(path); end

    # source://addressable//lib/addressable/uri.rb#671
    def normalized_encode(uri, return_type = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#114
    def parse(uri); end

    # source://addressable//lib/addressable/uri.rb#1376
    def port_mapping; end

    # source://addressable//lib/addressable/uri.rb#472
    def unencode(uri, return_type = T.unsafe(nil), leave_encoded = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#472
    def unencode_component(uri, return_type = T.unsafe(nil), leave_encoded = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#472
    def unescape(uri, return_type = T.unsafe(nil), leave_encoded = T.unsafe(nil)); end

    # source://addressable//lib/addressable/uri.rb#472
    def unescape_component(uri, return_type = T.unsafe(nil), leave_encoded = T.unsafe(nil)); end
  end
end

# source://addressable//lib/addressable/uri.rb#46
module Addressable::URI::CharacterClasses; end

# source://addressable//lib/addressable/uri.rb#47
Addressable::URI::CharacterClasses::ALPHA = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#57
Addressable::URI::CharacterClasses::AUTHORITY = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#48
Addressable::URI::CharacterClasses::DIGIT = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#60
Addressable::URI::CharacterClasses::FRAGMENT = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#49
Addressable::URI::CharacterClasses::GEN_DELIMS = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#56
Addressable::URI::CharacterClasses::HOST = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#58
Addressable::URI::CharacterClasses::PATH = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#54
Addressable::URI::CharacterClasses::PCHAR = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#59
Addressable::URI::CharacterClasses::QUERY = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#51
Addressable::URI::CharacterClasses::RESERVED = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#53
Addressable::URI::CharacterClasses::RESERVED_AND_UNRESERVED = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#55
Addressable::URI::CharacterClasses::SCHEME = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#50
Addressable::URI::CharacterClasses::SUB_DELIMS = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#52
Addressable::URI::CharacterClasses::UNRESERVED = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#72
module Addressable::URI::CharacterClassesRegexps; end

# source://addressable//lib/addressable/uri.rb#73
Addressable::URI::CharacterClassesRegexps::AUTHORITY = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#74
Addressable::URI::CharacterClassesRegexps::FRAGMENT = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#75
Addressable::URI::CharacterClassesRegexps::HOST = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#76
Addressable::URI::CharacterClassesRegexps::PATH = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#77
Addressable::URI::CharacterClassesRegexps::QUERY = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#78
Addressable::URI::CharacterClassesRegexps::RESERVED = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#79
Addressable::URI::CharacterClassesRegexps::RESERVED_AND_UNRESERVED = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#80
Addressable::URI::CharacterClassesRegexps::SCHEME = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#81
Addressable::URI::CharacterClassesRegexps::UNRESERVED = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#85
Addressable::URI::EMPTY_STR = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#34
class Addressable::URI::InvalidURIError < ::StandardError; end

# source://addressable//lib/addressable/uri.rb#2598
module Addressable::URI::NONE; end

# source://addressable//lib/addressable/uri.rb#1530
Addressable::URI::NORMPATH = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#63
module Addressable::URI::NormalizeCharacterClasses; end

# source://addressable//lib/addressable/uri.rb#68
Addressable::URI::NormalizeCharacterClasses::FRAGMENT = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#64
Addressable::URI::NormalizeCharacterClasses::HOST = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#66
Addressable::URI::NormalizeCharacterClasses::PCHAR = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#69
Addressable::URI::NormalizeCharacterClasses::QUERY = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#67
Addressable::URI::NormalizeCharacterClasses::SCHEME = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#65
Addressable::URI::NormalizeCharacterClasses::UNRESERVED = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#2427
Addressable::URI::PARENT = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#89
Addressable::URI::PORT_MAPPING = T.let(T.unsafe(nil), Hash)

# source://addressable//lib/addressable/uri.rb#2429
Addressable::URI::RULE_2A = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#2430
Addressable::URI::RULE_2B_2C = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#2431
Addressable::URI::RULE_2D = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#2432
Addressable::URI::RULE_PREFIXED_PARENT = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/uri.rb#2426
Addressable::URI::SELF_REF = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#360
Addressable::URI::SEQUENCE_ENCODING_TABLE = T.let(T.unsafe(nil), Array)

# source://addressable//lib/addressable/uri.rb#364
Addressable::URI::SEQUENCE_UPCASED_PERCENT_ENCODING_TABLE = T.let(T.unsafe(nil), Array)

# source://addressable//lib/addressable/uri.rb#84
Addressable::URI::SLASH = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/uri.rb#87
Addressable::URI::URIREGEX = T.let(T.unsafe(nil), Regexp)

# source://addressable//lib/addressable/version.rb#23
module Addressable::VERSION; end

# source://addressable//lib/addressable/version.rb#24
Addressable::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/version.rb#25
Addressable::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# source://addressable//lib/addressable/version.rb#28
Addressable::VERSION::STRING = T.let(T.unsafe(nil), String)

# source://addressable//lib/addressable/version.rb#26
Addressable::VERSION::TINY = T.let(T.unsafe(nil), Integer)
