inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - lib/generators/outbox/templates/*

inherit_gem:
  gc_ruboconfig: rubocop.yml

inherit_mode:
  merge:
    - Exclude

Gemspec/RequiredRubyVersion:
  Enabled: False

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 4
